default_agent: saldo_agent
agents:
  saldo_agent:
    name: saldo_agent
    entrypoint: my_agent.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::343075903304:role/agentcore-rds-saldo-agentcore-runtime
      execution_role_auto_create: true
      account: '343075903304'
      region: us-east-1
      ecr_repository: 343075903304.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-saldo_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: saldo_agent-NtGYVcCuUH
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:343075903304:runtime/saldo_agent-NtGYVcCuUH
      agent_session_id: 90251a3a-5716-41de-abd6-a75c08f812ad
    codebuild:
      project_name: bedrock-agentcore-saldo_agent-builder
      execution_role: arn:aws:iam::343075903304:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-0df63f78fa
      source_bucket: bedrock-agentcore-codebuild-sources-343075903304-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
